### PR TITLE
Big code cleanup

### PR DESCRIPTION
**Pull request by Gael-de-Sailly**
I've tried to clean the code as much as possible. I think we can't work correctly on a single file with over 2400 lines. That's for you :)
I've split `init.lua` into 7 files:
* the new `init.lua` that contains only the initialization functions and the processor functions (the libraries won't load on my computer, either before and after my changes, see #96), and calls the other files
* `nodes.lua`: registers the nodes
* `height_pixels.lua`: builds the height map from the image
* `mapgen.lua`: contains the function `realterrain.generate` and related functions
* `controller.lua`: various stuff related to the settings controller item and its formspecs
* `settings.lua`: settings default values, and related functions

I use local variables as much as possible. Using local variables when possible is recommended (faster).
A function is a type of variable like the others, it can be local.
Interesting feature concerning functions: a function can access **all** local variables defined higher **in the same file**.  That's why I've moved several functions between 2 files or between the top and the bottom of the same file in the commits `Local variables` to `local variables (4)`.

I use `pairs` and `ipairs` iterators instead of `next`. They are much more used in Lua.
`pairs(table)` is used like `next, table` to iterate over a table. Both have the same behaviour: they iterate over the table, but in a somewhat chaotic order.
`ipairs(table)` is similar except it works for **tables with numeral indexes that begin at 1**, and in the increasing order of these indexes.

The behaviour of the mod shouldn't have changed at all.

Please review it, and say if you think that something is misplaced. I would like you to feel at ease with the code (sorry if my English is not good…).

### CODE REVIEW

**Comment by Tank-ACiD** [comment]
nice, i'll be able to take a look at it / test it sunday and monday.

**Comment by 0-afflatus** [comment]
Surely all variables and functions that don't explicitly need to be global should be local?

**Comment by Gael-de-Sailly** [comment]
Security problem about [minetest.request_insecure_environment](https://github.com/minetest/minetest/blob/0851724/doc/lua_api.txt#L2437-L2442), that shouldn't be in a global variable. Fixing this.

**Comment by Gael-de-Sailly** [comment]
@0-afflatus: I think the only local variable that could be global is the function `show_rc_form`, that shows the formspec, if any other mod wants to use it, but that's very unlikely imo.

**Comment by Gael-de-Sailly** [comment]
The recent minetest commit [`4827ee1`](https://github.com/minetest/minetest/commit/4827ee1) may be annoying.

**Pull request merged**
